import type { QuestionDoc } from "@/types/question";

function opt(value: string, label: string) {
  return { value, label, id: value };
}

/** Default discovery survey with branching — used by seed script & admin "Load seed". */
export const SEED_QUESTIONS: Omit<
  QuestionDoc,
  "_id" | "createdAt" | "updatedAt"
>[] = [
  {
    key: "role",
    order: 1,
    type: "select",
    label: "Which best describes your role in hiring?",
    required: true,
    active: true,
    placeholder: "Select your role…",
    options: [
      opt("in_house", "In-house recruiter / Talent acquisition"),
      opt("agency", "Recruiting agency / Headhunter"),
      opt("hr_ops", "HR generalist / People ops"),
      opt("hiring_manager", "Hiring manager"),
      opt("founder", "Founder / Executive"),
      opt("other_role", "Other"),
    ],
  },
  {
    key: "role_other",
    order: 2,
    type: "text",
    label: "What is your role, in your own words?",
    required: true,
    active: true,
    placeholder: "e.g. Campus recruiting lead…",
    showIf: {
      logic: "and",
      conditions: [{ questionKey: "role", operator: "equals", value: "other_role" }],
    },
  },
  {
    key: "years_experience",
    order: 3,
    type: "select",
    label: "How many years have you worked in or around hiring?",
    required: true,
    active: true,
    placeholder: "Select…",
    options: [
      opt("lt2", "Less than 2 years"),
      opt("y2_5", "2–5 years"),
      opt("y6_10", "6–10 years"),
      opt("gt10", "More than 10 years"),
    ],
  },
  {
    key: "apps_per_role",
    order: 4,
    type: "select",
    label: "On a typical open role, roughly how many applications do you review?",
    required: true,
    active: true,
    placeholder: "Select…",
    options: [
      opt("under_50", "Under 50"),
      opt("a50_150", "50–150"),
      opt("a150_400", "150–400"),
      opt("over_400", "Over 400"),
    ],
  },
  {
    key: "screening_time",
    order: 5,
    type: "select",
    label: "How much of your week goes to CV / application screening?",
    required: true,
    active: true,
    placeholder: "Select…",
    options: [
      opt("lt5h", "Under 5 hours"),
      opt("h5_10", "5–10 hours"),
      opt("h10_20", "10–20 hours"),
      opt("gt20h", "More than 20 hours"),
    ],
    showIf: {
      logic: "or",
      conditions: [
        { questionKey: "apps_per_role", operator: "equals", value: "a150_400" },
        { questionKey: "apps_per_role", operator: "equals", value: "over_400" },
      ],
    },
  },
  {
    key: "missed_talent_fear",
    order: 6,
    type: "single_choice",
    label: "When volume is high, what worries you most?",
    required: true,
    active: true,
    options: [
      opt("miss_good", "Missing a great candidate in the pile"),
      opt("inconsistent", "Inconsistent screening quality across the team"),
      opt("slow_hire", "Hiring too slowly and losing candidates"),
      opt("bias", "Bias creeping into quick screens"),
      opt("other_worry", "Something else"),
    ],
    showIf: {
      logic: "and",
      conditions: [
        { questionKey: "apps_per_role", operator: "equals", value: "over_400" },
      ],
    },
  },
  {
    key: "agency_placements",
    order: 7,
    type: "select",
    label: "Roughly how many placements does your desk / team target per month?",
    required: true,
    active: true,
    placeholder: "Select…",
    options: [
      opt("p1_3", "1–3"),
      opt("p4_8", "4–8"),
      opt("p9_15", "9–15"),
      opt("p16_plus", "16+"),
    ],
    showIf: {
      logic: "and",
      conditions: [{ questionKey: "role", operator: "equals", value: "agency" }],
    },
  },
  {
    key: "hm_involvement",
    order: 8,
    type: "single_choice",
    label: "How involved are you in the first CV screen today?",
    required: true,
    active: true,
    options: [
      opt("do_it_myself", "I do most of it myself"),
      opt("review_shortlist", "I review a shortlist someone else prepares"),
      opt("light_touch", "Light touch — I jump in late"),
      opt("not_involved", "Barely involved in screening"),
    ],
    showIf: {
      logic: "or",
      conditions: [
        { questionKey: "role", operator: "equals", value: "hiring_manager" },
        { questionKey: "role", operator: "equals", value: "founder" },
      ],
    },
  },
  {
    key: "team_size_hiring",
    order: 9,
    type: "select",
    label: "How many people are actively involved in hiring decisions at your company?",
    required: true,
    active: true,
    placeholder: "Select…",
    options: [
      opt("solo", "Just me"),
      opt("t2_5", "2–5 people"),
      opt("t6_15", "6–15 people"),
      opt("t16_plus", "16+ people"),
    ],
    showIf: {
      logic: "or",
      conditions: [
        { questionKey: "role", operator: "equals", value: "hr_ops" },
        { questionKey: "role", operator: "equals", value: "in_house" },
        { questionKey: "role", operator: "equals", value: "founder" },
      ],
    },
  },
  {
    key: "biggest_pain",
    order: 10,
    type: "single_choice",
    label: "What’s the single most painful part of recruiting for you right now?",
    required: true,
    active: true,
    options: [
      opt("cv_volume", "CV / application volume"),
      opt("shortlist_quality", "Shortlist quality"),
      opt("scheduling", "Scheduling interviews"),
      opt("no_shows", "No-shows / ghosting"),
      opt("video_interview_load", "Video interview load"),
      opt("sourcing", "Sourcing enough talent"),
      opt("stakeholder_alignment", "Stakeholder alignment"),
      opt("other_pain", "Something else"),
    ],
  },
  {
    key: "pain_detail",
    order: 11,
    type: "textarea",
    label: "Tell us a bit more about that pain — what does a bad week look like?",
    required: true,
    active: true,
    placeholder:
      "e.g. I get 300 applications per role and screening them eats my whole week…",
  },
  {
    key: "pain_other",
    order: 12,
    type: "text",
    label: "What is that ‘something else’ pain?",
    required: true,
    active: true,
    showIf: {
      logic: "and",
      conditions: [
        { questionKey: "biggest_pain", operator: "equals", value: "other_pain" },
      ],
    },
  },
  {
    key: "must_haves",
    order: 13,
    type: "multi_choice",
    label: "What would make Shortlist a must-have for you?",
    hint: "Pick everything that applies.",
    required: true,
    active: true,
    options: [
      opt("faster_cv", "Faster CV screening"),
      opt("better_shortlists", "Better quality shortlists"),
      opt("less_bias", "Less bias, more consistency"),
      opt("outreach_scheduling", "Automated outreach & scheduling"),
      opt("reporting", "Reporting for stakeholders"),
      opt("sourcing", "Sourcing new candidates"),
      opt("ai_video", "AI-assisted video interviewing"),
    ],
  },
  {
    key: "video_interview_today",
    order: 14,
    type: "single_choice",
    label: "Do you already use video interviews in your hiring process?",
    required: true,
    active: true,
    options: [
      opt("yes_live", "Yes — live video interviews"),
      opt("yes_async", "Yes — async / recorded video"),
      opt("yes_both", "Yes — both live and async"),
      opt("not_yet", "Not yet"),
      opt("no_plans", "No, and no plans"),
    ],
    showIf: {
      logic: "or",
      conditions: [
        { questionKey: "must_haves", operator: "includes", value: "ai_video" },
        {
          questionKey: "biggest_pain",
          operator: "equals",
          value: "video_interview_load",
        },
      ],
    },
  },
  {
    key: "video_pain",
    order: 15,
    type: "multi_choice",
    label: "Where does video interviewing hurt most today?",
    hint: "Pick everything that applies.",
    required: true,
    active: true,
    options: [
      opt("time_to_review", "Time to review recordings"),
      opt("inconsistent_scoring", "Inconsistent scoring across interviewers"),
      opt("scheduling_chaos", "Scheduling chaos"),
      opt("candidate_dropoff", "Candidate drop-off"),
      opt("note_taking", "Note-taking and summaries"),
      opt("other_video", "Something else"),
    ],
    showIf: {
      logic: "or",
      conditions: [
        {
          questionKey: "video_interview_today",
          operator: "equals",
          value: "yes_live",
        },
        {
          questionKey: "video_interview_today",
          operator: "equals",
          value: "yes_async",
        },
        {
          questionKey: "video_interview_today",
          operator: "equals",
          value: "yes_both",
        },
      ],
    },
  },
  {
    key: "video_ai_expectation",
    order: 16,
    type: "textarea",
    label: "If AI assisted your video interviews, what should it do first?",
    required: true,
    active: true,
    placeholder: "e.g. Score answers against a rubric and flag red flags…",
    showIf: {
      logic: "or",
      conditions: [
        { questionKey: "must_haves", operator: "includes", value: "ai_video" },
        {
          questionKey: "video_interview_today",
          operator: "equals",
          value: "not_yet",
        },
      ],
    },
  },
  {
    key: "cv_ai_trust",
    order: 17,
    type: "single_choice",
    label: "For AI CV screening, what would you need before you’d trust it?",
    required: true,
    active: true,
    options: [
      opt("written_reasons", "Written reasons for every score"),
      opt("human_override", "Easy human overrides that teach the model"),
      opt("audit_trail", "An audit trail for compliance"),
      opt("pilot_proof", "Proof it works on my roles in a pilot"),
      opt("not_sure", "Not sure yet"),
    ],
    showIf: {
      logic: "or",
      conditions: [
        { questionKey: "must_haves", operator: "includes", value: "faster_cv" },
        {
          questionKey: "must_haves",
          operator: "includes",
          value: "better_shortlists",
        },
        {
          questionKey: "biggest_pain",
          operator: "equals",
          value: "cv_volume",
        },
      ],
    },
  },
  {
    key: "willingness_to_pay",
    order: 18,
    type: "single_choice",
    label:
      "If Shortlist clearly fixed your biggest pain, what would you pay per month?",
    required: true,
    active: true,
    options: [
      opt("under_25", "Under $25"),
      opt("b25_75", "$25–$75"),
      opt("b75_200", "$75–$200"),
      opt("b200_500", "$200–$500"),
      opt("b500_plus", "$500+"),
    ],
  },
  {
    key: "budget_share",
    order: 19,
    type: "select",
    label:
      "What share of your monthly software / subscriptions budget would that be?",
    required: true,
    active: true,
    placeholder: "Select…",
    options: [
      opt("under_5", "Under 5% — barely noticeable"),
      opt("p5_15", "5–15% — meaningful but fine"),
      opt("p15_30", "15–30% — a serious line item"),
      opt("over_30", "Over 30% — it would need to replace other tools"),
      opt("no_budget", "I don’t control a budget"),
    ],
  },
  {
    key: "buyer",
    order: 20,
    type: "single_choice",
    label: "Who usually approves a tool like this?",
    required: true,
    active: true,
    options: [
      opt("me", "Me"),
      opt("my_manager", "My manager"),
      opt("hr_lead", "HR / People lead"),
      opt("finance", "Finance / procurement"),
      opt("founder_ceo", "Founder / CEO"),
      opt("unclear", "Unclear / varies"),
    ],
    showIf: {
      logic: "or",
      conditions: [
        {
          questionKey: "budget_share",
          operator: "equals",
          value: "no_budget",
        },
        {
          questionKey: "role",
          operator: "equals",
          value: "hiring_manager",
        },
      ],
    },
  },
  {
    key: "current_stack",
    order: 21,
    type: "multi_choice",
    label: "What do you use today for recruiting?",
    hint: "Pick everything that applies.",
    required: true,
    active: true,
    options: [
      opt("ats", "ATS (Greenhouse, Lever, Workable, etc.)"),
      opt("linkedin", "LinkedIn Recruiter"),
      opt("email_inbox", "Email / shared inbox"),
      opt("spreadsheets", "Spreadsheets"),
      opt("job_boards", "Job boards"),
      opt("video_tool", "Dedicated video interview tool"),
      opt("other_stack", "Other"),
    ],
  },
  {
    key: "ats_name",
    order: 22,
    type: "text",
    label: "Which ATS, if you’re willing to say?",
    required: false,
    active: true,
    placeholder: "e.g. Greenhouse",
    showIf: {
      logic: "and",
      conditions: [
        { questionKey: "current_stack", operator: "includes", value: "ats" },
      ],
    },
  },
  {
    key: "pilot_interest",
    order: 23,
    type: "single_choice",
    label: "Would you join a free pilot if we built around your workflow?",
    required: true,
    active: true,
    options: [
      opt("yes_asap", "Yes — as soon as possible"),
      opt("yes_later", "Yes — later this year"),
      opt("maybe", "Maybe — send me details"),
      opt("no", "No thanks"),
    ],
  },
  {
    key: "email",
    order: 24,
    type: "email",
    label: "Where should we send your pilot invite / follow-up?",
    required: true,
    active: true,
    placeholder: "you@company.com",
    showIf: {
      logic: "or",
      conditions: [
        {
          questionKey: "pilot_interest",
          operator: "equals",
          value: "yes_asap",
        },
        {
          questionKey: "pilot_interest",
          operator: "equals",
          value: "yes_later",
        },
        { questionKey: "pilot_interest", operator: "equals", value: "maybe" },
      ],
    },
  },
  {
    key: "company_context",
    order: 25,
    type: "text",
    label: "Company or agency name (optional)",
    required: false,
    active: true,
    placeholder: "Acme Recruiting",
    showIf: {
      logic: "and",
      conditions: [{ questionKey: "email", operator: "answered" }],
    },
  },
];
